# Last Update:2017-03-20 15:37:41
#########################################################################
# File Name: Makefile
# Author: wangchenxi
# mail: chinawangchenxi@gmail.com
# Created Time: 2017年03月20日 星期一 15时37分41秒
# brief:
#########################################################################
accumulate:accumulate.o
	g++ accumulate.o -o accumulate
accumulate.o:accumulate.cpp
	g++ -g -c accumulate.cpp
.PHONY:clean
clean:
	rm -rf *.o accumulate
