# Last Update:2017-03-22 15:58:26
#########################################################################
# File Name: Makefile
# Author: wangchenxi
# mail: chinawangchenxi@gmail.com
# Created Time: 2017年03月22日 星期三 15时58分26秒
# brief:
#########################################################################
KMP:get_next_arry.o
	g++  get_next_arry.o -o KMP
get_next_arry.o:get_next_arry.cpp
	g++ -g -c get_next_arry.cpp
.PHONY:clean
clean:
	rm -rf KMP *.o
