// Last Update:2017-04-04 15:40:10
/**
 * @file 1.c
 * @brief 
 * @author wangchenxi
 * @version 0.1.00
 * @date 2017-04-04
 */

#include <stdlib.h>
#include <syslog.h>
#include <unistd.h>
#include <stdio.h>


int main(int argc, char **argv) {
    int i = 0;
    int n = atoi(argv[1]);
    while(1)
    {
        openlog("zooyo", LOG_CONS , LOG_LOCAL7);
        syslog(LOG_INFO, "This is a syslog test message generated by program %sn", argv[0]);
        closelog();
        ++i;
        if(i%n == 0)
        {
            printf("________%d____________--------------_____\n", i);
            break;
        }
    }
    return 0;
}


